import { AlertTriangle, Bell, DollarSign,Target } from "lucide-react"

import { Address, AddressStat } from "./types"

export const mockMonitoredAddresses: Address[] = [
  {
    id: "ADDR-001",
    address: "1A1zP1eP5QGefi2DMPTfTL5SLmv7DivfNa",
    blockchain: "Bitcoin",
    label: "Suspicious Exchange Wallet",
    category: "HIGH_RISK",
    riskScore: 95,
    status: "ACTIVE",
    alertsEnabled: true,
    dateAdded: "2025-06-01",
    lastActivity: "2 hours ago",
    totalTransactions: 1247,
    totalVolume: "$2,450,000",
    tags: ["Exchange", "High-Volume", "Sanctions"],
    notes: "Flagged for potential sanctions evasion activities",
    alertThreshold: 10000,
    monitoringReason: "OFAC sanctions match",
    addedBy: "Sarah Chen",
  },
  {
    id: "ADDR-002",
    address: "3J98t1WpEZ73CNmQviecrnyiWrnqRhWNLy",
    blockchain: "Bitcoin",
    label: "Mixer Service Input",
    category: "CRITICAL",
    riskScore: 98,
    status: "ACTIVE",
    alertsEnabled: true,
    dateAdded: "2025-05-28",
    lastActivity: "15 minutes ago",
    totalTransactions: 892,
    totalVolume: "$1,890,000",
    tags: ["Mixer", "Privacy", "Critical"],
    notes: "Known cryptocurrency mixing service - high priority monitoring",
    alertThreshold: 5000,
    monitoringReason: "Cryptocurrency mixer detection",
    addedBy: "Michael Rodriguez",
  },
  {
    id: "ADDR-003",
    address: "0x742d35Cc6634C0532925a3b8D4C9db96DfB3f681",
    blockchain: "Ethereum",
    label: "DeFi Protocol Exploit",
    category: "MEDIUM",
    riskScore: 72,
    status: "ACTIVE",
    alertsEnabled: false,
    dateAdded: "2025-06-05",
    lastActivity: "1 day ago",
    totalTransactions: 156,
    totalVolume: "$340,000",
    tags: ["DeFi", "Exploit", "Investigation"],
    notes: "Address involved in recent DeFi protocol exploit",
    alertThreshold: 25000,
    monitoringReason: "Security incident investigation",
    addedBy: "Emma Thompson",
  },
  {
    id: "ADDR-004",
    address: "bc1qxy2kgdygjrsqtzq2n0yrf2493p83kkfjhx0wlh",
    blockchain: "Bitcoin",
    label: "PEP-Related Wallet",
    category: "HIGH_RISK",
    riskScore: 85,
    status: "PAUSED",
    alertsEnabled: true,
    dateAdded: "2025-05-15",
    lastActivity: "3 days ago",
    totalTransactions: 45,
    totalVolume: "$125,000",
    tags: ["PEP", "Political", "Enhanced-DD"],
    notes: "Wallet associated with politically exposed person",
    alertThreshold: 15000,
    monitoringReason: "PEP association",
    addedBy: "David Kim",
  },
  {
    id: "ADDR-005",
    address: "0x8ba1f109551bD432803012645Hac136c22C501e3",
    blockchain: "Ethereum",
    label: "Ransomware Payment Address",
    category: "CRITICAL",
    riskScore: 99,
    status: "ACTIVE",
    alertsEnabled: true,
    dateAdded: "2025-06-10",
    lastActivity: "6 hours ago",
    totalTransactions: 23,
    totalVolume: "$89,000",
    tags: ["Ransomware", "Criminal", "Law-Enforcement"],
    notes: "Address linked to ransomware payments - law enforcement coordination",
    alertThreshold: 1000,
    monitoringReason: "Criminal activity",
    addedBy: "Sarah Chen",
  },
]

export const addressStats: AddressStat[] = [
  { label: "Total Monitored", value: 247, change: "+12", icon: Target },
  { label: "High Risk", value: 89, change: "+5", icon: AlertTriangle },
  { label: "Active Alerts", value: 34, change: "+8", icon: Bell },
  { label: "Total Volume", value: "$12.4M", change: "+2.1M", icon: DollarSign },
]