import jsPDF from 'jspdf';
import 'jspdf-autotable';
import type { jsPDF } from 'jspdf';

export interface ReportData {
  transaction: any;
  modules: any[];
  metadata: {
    reportId: string;
    generatedAt: string;
    generatedBy: string;
  };
}

export const generatePDF = async (reportData: ReportData, modules: any[]): Promise<void> => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 20;
  let yPosition = margin;

  // Helper function to add text with word wrapping
  const addText = (text: string, x: number, y: number, maxWidth: number, fontSize: number = 12) => {
    doc.setFontSize(fontSize);
    const lines = doc.splitTextToSize(text, maxWidth);
    doc.text(lines, x, y);
    return y + (lines.length * fontSize * 0.4);
  };

  // Helper function to add a new page if needed
  const checkNewPage = (requiredHeight: number) => {
    if (yPosition + requiredHeight > doc.internal.pageSize.getHeight() - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // Report Header
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Compliance Case Report', margin, yPosition);
  yPosition += 15;

  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(`Report ID: ${reportData.metadata.reportId}`, margin, yPosition);
  yPosition += 8;
  doc.text(`Generated: ${new Date(reportData.metadata.generatedAt).toLocaleString()}`, margin, yPosition);
  yPosition += 8;
  doc.text(`Generated By: ${reportData.metadata.generatedBy}`, margin, yPosition);
  yPosition += 20;

  // Add a line separator
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;

  // Process each module
  modules
    .sort((a, b) => a.position - b.position)
    .forEach((module, index) => {
      checkNewPage(50); // Reserve space for module

      // Module header
      doc.setFontSize(16);
      doc.setFont('helvetica', 'bold');
      doc.text(`${index + 1}. ${module.title}`, margin, yPosition);
      yPosition += 15;

      // Module content based on type
      switch (module.type) {
        case 'transaction-info':
          yPosition = renderTransactionInfo(doc, reportData.transaction, margin, yPosition, pageWidth);
          break;
        case 'transaction-risk':
          yPosition = renderTransactionRisk(doc, reportData.transaction, margin, yPosition, pageWidth);
          break;
        case 'counterparty-info':
          yPosition = renderCounterpartyInfo(doc, reportData.transaction, margin, yPosition, pageWidth);
          break;
        case 'notes':
          yPosition = renderNotes(doc, module, margin, yPosition, pageWidth);
          break;
        case 'image':
          yPosition = renderImage(doc, module, margin, yPosition, pageWidth);
          break;
        case 'text':
          yPosition = renderText(doc, module, margin, yPosition, pageWidth);
          break;
        case 'chart':
          yPosition = renderChart(doc, module, margin, yPosition, pageWidth);
          break;
        default:
          yPosition = addText('Unknown module type', margin, yPosition, pageWidth - 2 * margin);
      }

      yPosition += 20; // Space between modules
    });

  // Report footer
  checkNewPage(30);
  doc.setLineWidth(0.5);
  doc.line(margin, yPosition, pageWidth - margin, yPosition);
  yPosition += 15;

  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('This report was generated by the Compliance Screener system', margin, yPosition);
  yPosition += 8;
  doc.text('For questions or concerns, please contact the compliance team', margin, yPosition);

  // Save the PDF
  doc.save(`case-report-${reportData.metadata.reportId}.pdf`);
};

const renderTransactionInfo = (doc: jsPDF, transaction: any, margin: number, yPosition: number, pageWidth: number): number => {
  const data = [
    ['Transaction ID', transaction.txId],
    ['Client ID', transaction.clientId || 'N/A'],
    ['Blockchain', transaction.blockchain],
    ['Amount', `${(transaction.amount / 100000000).toFixed(8)} BTC`],
    ['Timestamp', new Date(transaction.timestamp).toLocaleString()],
    ['Status', transaction.status || 'PENDING']
  ];

  doc.autoTable({
    startY: yPosition,
    head: [['Field', 'Value']],
    body: data,
    theme: 'grid',
    headStyles: { fillColor: [66, 139, 202] },
    margin: { left: margin, right: margin },
    styles: { fontSize: 10 }
  });

  return (doc as any).lastAutoTable.finalY + 10;
};

const renderTransactionRisk = (doc: jsPDF, transaction: any, margin: number, yPosition: number, pageWidth: number): number => {
  const riskScores = [
    ['Overall Risk', transaction.riskScores?.[0] || 25],
    ['Entity Risk', 23],
    ['Jurisdiction Risk', 25],
    ['Transaction Risk', 15]
  ];

  doc.autoTable({
    startY: yPosition,
    head: [['Risk Category', 'Score']],
    body: riskScores,
    theme: 'grid',
    headStyles: { fillColor: [220, 53, 69] },
    margin: { left: margin, right: margin },
    styles: { fontSize: 10 }
  });

  return (doc as any).lastAutoTable.finalY + 10;
};

const renderCounterpartyInfo = (doc: jsPDF, transaction: any, margin: number, yPosition: number, pageWidth: number): number => {
  const counterparties = [
    ['Entity Name', 'Crypto Exchange Ltd'],
    ['Entity Type', 'Exchange'],
    ['Contact Email', 'compliance@cryptoexchange.com'],
    ['Website', 'https://cryptoexchange.com'],
    ['Status', 'Verified']
  ];

  doc.autoTable({
    startY: yPosition,
    head: [['Field', 'Value']],
    body: counterparties,
    theme: 'grid',
    headStyles: { fillColor: [40, 167, 69] },
    margin: { left: margin, right: margin },
    styles: { fontSize: 10 }
  });

  return (doc as any).lastAutoTable.finalY + 10;
};

const renderNotes = (doc: jsPDF, module: any, margin: number, yPosition: number, pageWidth: number): number => {
  const notes = [
    {
      title: 'Initial Review',
      content: 'Transaction appears to be a standard exchange transfer. No immediate red flags identified.',
      author: 'John Smith',
      date: new Date().toLocaleString()
    },
    {
      title: 'Risk Assessment',
      content: 'Low risk transaction based on counterparty verification and amount. Proceeding with standard processing.',
      author: 'Sarah Johnson',
      date: new Date(Date.now() - 3600000).toLocaleString()
    }
  ];

  notes.forEach(note => {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(note.title, margin, yPosition);
    yPosition += 8;

    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    yPosition = addText(note.content, margin, yPosition, pageWidth - 2 * margin, 10);
    yPosition += 5;

    doc.setFontSize(8);
    doc.text(`By ${note.author} on ${note.date}`, margin, yPosition);
    yPosition += 15;
  });

  return yPosition;
};

const renderImage = (doc: jsPDF, module: any, margin: number, yPosition: number, pageWidth: number): number => {
  if (module.content?.imageUrl) {
    try {
      // For base64 images, we can embed them directly
      if (module.content.imageUrl.startsWith('data:image')) {
        const img = new Image();
        img.onload = () => {
          const imgWidth = 100;
          const imgHeight = (img.height * imgWidth) / img.width;
          doc.addImage(module.content.imageUrl, 'JPEG', margin, yPosition, imgWidth, imgHeight);
        };
        img.src = module.content.imageUrl;
        yPosition += 80; // Reserve space for image
      } else {
        doc.text('Image URL provided (not embedded in PDF)', margin, yPosition);
        yPosition += 10;
      }
    } catch (error) {
      doc.text('Error loading image', margin, yPosition);
      yPosition += 10;
    }
  } else {
    doc.text('No image uploaded', margin, yPosition);
    yPosition += 10;
  }

  if (module.content?.caption) {
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text(module.content.caption, margin, yPosition);
    yPosition += 8;
  }

  return yPosition;
};

const renderText = (doc: jsPDF, module: any, margin: number, yPosition: number, pageWidth: number): number => {
  if (module.content?.title) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(module.content.title, margin, yPosition);
    yPosition += 10;
  }

  if (module.content?.text) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    yPosition = addText(module.content.text, margin, yPosition, pageWidth - 2 * margin, 10);
  }

  return yPosition;
};

const renderChart = (doc: jsPDF, module: any, margin: number, yPosition: number, pageWidth: number): number => {
  if (module.content?.title) {
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(module.content.title, margin, yPosition);
    yPosition += 10;
  }

  if (module.content?.data && module.content.data.length > 0) {
    const data = module.content.data.map((item: any) => [item.label, item.value.toString()]);
    
    doc.autoTable({
      startY: yPosition,
      head: [['Category', 'Value']],
      body: data,
      theme: 'grid',
      headStyles: { fillColor: [108, 117, 125] },
      margin: { left: margin, right: margin },
      styles: { fontSize: 10 }
    });

    return (doc as any).lastAutoTable.finalY + 10;
  } else {
    doc.text('No chart data available', margin, yPosition);
    return yPosition + 10;
  }
};